// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXyJWg0hQhr88MeeqRPiiDHGG4KM23KwI',
    appId: '1:922934256876:web:11de0bd30a3544c21631c9',
    messagingSenderId: '922934256876',
    projectId: 'brawl-tcg-database',
    authDomain: 'brawl-tcg-database.firebaseapp.com',
    storageBucket: 'brawl-tcg-database.firebasestorage.app',
    measurementId: 'G-L20RMVTS6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuQpPASftFofIzn8mWHgsAWmGFDOwAiE4',
    appId: '1:922934256876:android:f0087aac4a3ee8921631c9',
    messagingSenderId: '922934256876',
    projectId: 'brawl-tcg-database',
    storageBucket: 'brawl-tcg-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlxzk04_sDlx_P3WRU-lb3rDTQg5CUwlQ',
    appId: '1:922934256876:ios:21a85f36bde4c56e1631c9',
    messagingSenderId: '922934256876',
    projectId: 'brawl-tcg-database',
    storageBucket: 'brawl-tcg-database.firebasestorage.app',
    iosBundleId: 'com.example.brawlTcg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlxzk04_sDlx_P3WRU-lb3rDTQg5CUwlQ',
    appId: '1:922934256876:ios:21a85f36bde4c56e1631c9',
    messagingSenderId: '922934256876',
    projectId: 'brawl-tcg-database',
    storageBucket: 'brawl-tcg-database.firebasestorage.app',
    iosBundleId: 'com.example.brawlTcg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXyJWg0hQhr88MeeqRPiiDHGG4KM23KwI',
    appId: '1:922934256876:web:ef9142e645e4c5fb1631c9',
    messagingSenderId: '922934256876',
    projectId: 'brawl-tcg-database',
    authDomain: 'brawl-tcg-database.firebaseapp.com',
    storageBucket: 'brawl-tcg-database.firebasestorage.app',
    measurementId: 'G-1W8N4RE5K3',
  );
}
